CREATE TABLE CLIENTE (
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(100),
  ESTADO CHAR(2),
  CEP CHAR(9),
  TELEFONE CHAR(14),
  CONTATO VARCHAR(30),
  PRIMARY KEY (CNPJ)
);

CREATE TABLE PEDIDO (
  NUMERO INT NOT NULL,
  DATA_PEDIDO DATE NOT NULL,
  VALOR_TOTAL DECIMAL(10, 2),
  CNPJ CHAR(18) NOT NULL,
  PRIMARY KEY (NUMERO),
  FOREIGN KEY (CNPJ) REFERENCES CLIENTE(CNPJ)
);

CREATE TABLE MEDICAMENTO (
  CODIGO INT NOT NULL,
  TIPO CHAR(1) NOT NULL,
  DATA_VALIDADE DATE NOT NULL,
  NOME VARCHAR(100),
  PRINCIPIO_ATIVO VARCHAR(100),
  COR_TARJA VARCHAR(20),
  LABORATORIO INT NOT NULL,
  PRIMARY KEY (CODIGO),
  FOREIGN KEY (LABORATORIO) REFERENCES LABORATORIO(CODIGO)
);

CREATE TABLE ITEM (
  ITEM INT NOT NULL,
  PEDIDO INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  PRECO NUMERIC(10, 2),
  MEDICAMENTO INT NOT NULL,
  PRIMARY KEY (ITEM, PEDIDO),
  FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(NUMERO),
  FOREIGN KEY (MEDICAMENTO) REFERENCES MEDICAMENTO(CODIGO)
);

CREATE TABLE LABORATORIO (
  CODIGO INT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  PRIMARY KEY (CODIGO)
);
